const actions = { 
    SET_USER_INFO: 'SET_USER_INFO',

    GET_FILMS_LIST_STARTED: 'GET_FILMS_LIST_STARTED',
    GET_FILMS_LIST_SUCCESS: 'GET_FILMS_LIST_SUCCESS',
    GET_FILMS_LIST_FAILURE: 'GET_FILMS_LIST_FAILURE',

    GET_FILM_INFO_STARTED: 'GET_FILM_INFO_STARTED',
    GET_FILM_INFO_SUCCESS: 'GET_FILM_INFO_SUCCESS',
    GET_FILM_INFO_FAILURE: 'GET_FILM_INFO_FAILURE',

    SET_LOADING_FALSE: 'SET_LOADING_FALSE',
}

export default actions;